// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Rh1RBr0QtCT8ZFzMYn5qCAQXkwWJDag',
    appId: '1:850711888153:web:37515555825b9eb3588588',
    messagingSenderId: '850711888153',
    projectId: 'chat-app-17af1',
    authDomain: 'chat-app-17af1.firebaseapp.com',
    storageBucket: 'chat-app-17af1.appspot.com',
    measurementId: 'G-1PTGNCCNFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1v5CrD8u5_Ct7acvpsnIh4QQ6OxYUWbM',
    appId: '1:850711888153:android:40f4cdbe1d07c151588588',
    messagingSenderId: '850711888153',
    projectId: 'chat-app-17af1',
    storageBucket: 'chat-app-17af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb224kv-Gh48-GF910jZvddtsQcK34mb0',
    appId: '1:850711888153:ios:1b0ec9ffbd2d454c588588',
    messagingSenderId: '850711888153',
    projectId: 'chat-app-17af1',
    storageBucket: 'chat-app-17af1.appspot.com',
    iosClientId: '850711888153-p08it02huifq4ocng3jer21aonvqnlo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb224kv-Gh48-GF910jZvddtsQcK34mb0',
    appId: '1:850711888153:ios:e4bfa469e7e298eb588588',
    messagingSenderId: '850711888153',
    projectId: 'chat-app-17af1',
    storageBucket: 'chat-app-17af1.appspot.com',
    iosClientId: '850711888153-g7c6vej7ol0810p4kfgek51j6vi30a72.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
